#! /usr/bin/env python
# encoding: utf-8
# Copyright 2025 Alibek Omarov
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

from waflib import Logs, Configure
from waflib.extras import gitversion

def options(opt):
	return

@Configure.conf
def get_git_commit_date(conf):
	node = conf.srcnode.find_node('.git')

	if not node:
		Logs.debug('can\'t find .git in conf.srcnode')
		return None

	return gitversion.run_git(conf, ['log', '-1', '--format=%ci'])

def configure(conf):
	conf.load('gitversion')

	conf.start_msg('Git commit date')
	conf.env.GIT_COMMIT_DATE = conf.get_git_commit_date()
	conf.end_msg(conf.env.GIT_COMMIT_DATE)

def build(bld):
	bld(name = 'qcommon_includes', export_includes = '.')

	bld.stlib(source = bld.path.ant_glob('*.c'),
		target = 'qcommon',
		use = 'qcommon_includes')
