#! /usr/bin/env python
# encoding: utf-8
# Copyright 2025 Alibek Omarov
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

from waflib import Logs, Configure
from waflib.extras import gitversion

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	bld.program(source = bld.path.ant_glob('*.c'), target = 'null', use='engine M')
